# Generated by Django 4.1.7 on 2023-02-18 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.TextField(help_text='Rua X, qd 55 lt X, bairro xxx Cidade/Estado')),
                ('telefone', models.CharField(help_text='(62) 9999-9999', max_length=15)),
                ('debito', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Débito R$')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('qnt_marmita', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade de marmitas')),
                ('valor_marmita', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor und marmita R$')),
                ('descricao', models.TextField(default='0', verbose_name='descrição')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_pago', models.CharField(choices=[('s', 'sim'), ('n', 'não')], default='n', max_length=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
        ),
    ]
